name: Manage Testing Project

on:
  project_card:
    types:
      - moved
  pull_request:
    types:
      - labeled

jobs:
  manage-testing-project:
    runs-on: ubuntu-latest
    steps:
      - name: Handle event
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
          elif [ "${{ github.event_name }}" == "project_card" ]; then
          else
            echo 'Event type not supported'
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
